[package]
name = "nym"
version = "0.0.0"
authors = ["Sean Olson <olson.sean.k@gmail.com>"]
edition = "2018"

[lib]

[[bin]]
name = "nym"

[dependencies]
anyhow = "^1.0.0"
bimap = "^0.5.0"
nom = "^5.1.0"
normpath = "^0.1.0"
regex = "^1.4.0"
structopt = "^0.3.0"
thiserror = "^1.0.0"
walkdir = "^2.3.0"
